// Generated by CoffeeScript 1.7.1
(function() {
  var caser, lineCounter, split, through;

  split = require('split');

  through = require('through');

  lineCounter = 0;

  caser = function(text) {
    lineCounter++;
    if (lineCounter % 2 === 0) {
      return text.toUpperCase();
    }
    return text.toLowerCase();
  };

  process.stdin.pipe(split()).pipe(through(function(line) {
    var final;
    final = caser(line.toString());
    return this.queue(final + '\n');
  })).pipe(process.stdout);

}).call(this);

//# sourceMappingURL=5-lines.map
